# Generated by Django 6.0.6 on 2026-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=700)),
                ('paragraph', models.TextField()),
                ('train_number', models.IntegerField()),
                ('stu_num', models.IntegerField()),
                ('expfac_num', models.IntegerField()),
                ('course_num', models.IntegerField()),
            ],
        ),
    ]
