# Generated by Django 4.2 on 2026-06-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=700)),
                ('paragraph', models.TextField()),
                ('train_number', models.IntegerField()),
                ('train_dis', models.CharField(max_length=300)),
                ('stu_num', models.IntegerField()),
                ('selc_dis', models.CharField(max_length=300)),
                ('expfac_num', models.IntegerField()),
                ('expfac_dis', models.CharField(max_length=300)),
                ('course_num', models.IntegerField()),
                ('course_dis', models.CharField(max_length=300)),
            ],
        ),
    ]