# Generated by Django 4.2 on 2026-06-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutdahanraj',
            name='course_dis',
        ),
        migrations.RemoveField(
            model_name='aboutdahanraj',
            name='expfac_dis',
        ),
        migrations.RemoveField(
            model_name='aboutdahanraj',
            name='selc_dis',
        ),
        migrations.RemoveField(
            model_name='aboutdahanraj',
            name='train_dis',
        ),
    ]
